services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8443:8443"

  frontend:
    build:
      context: ./frontend-ang
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"

