# Exported from Render on 2025-09-16T17:02:06Z
version: "1"
services:
- type: web
  name: gestion-de-parc_informatique
  runtime: docker
  repo: https://github.com/dhieeddine/gestion-de-parc_informatique
  branch: ma-nouvelle-branche
  plan: free
  envVars:
  - key: port
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: "off"
